[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
cmds = [
  "cd GoHardAPI",
  "dotnet publish -c Release -o out"
]

[start]
cmd = "cd GoHardAPI/out && ./GoHardAPI --urls http://0.0.0.0:$PORT"
